article/urls.py
from django.conf.urls import url
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^article_column/$', views.article_column, name='article_column'),
    url(r'^rename_column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del_column/$', views.del_article_column, name="del_article_column"),
    url(r'^article_post/$', views.article_post, name="article_post"),
    url(r'^article_list/$', views.article_list, name="article_list"),
    url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)$', views.article_detail, name="article_detail"),
    url(r'^del_article/$', views.del_article, name="del_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_article'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
]

article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

article/forms.py
from django import forms

from article.models import ArticleColumn, ArticlePost


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

article/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from article.forms import ArticleColumnForm, ArticlePostForm
from article.models import ArticleColumn, ArticlePost


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, "column_form": column_form})

    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, 'article/column/article_post.html',
                      {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url='/account/login')
def article_list(request):
    articles = ArticlePost.objects.filter(author=request.user)
    return render(request, "article/column/article_list.html", {"articles": articles})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

templates/article/column/article_column.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title %}article column{% endblock %}

{% block content %}
    <div>
        <p class="text-right">
            <button id="add_column" class="btn btn-primary" onclick="add_column()">add column</button>
        </p>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>栏目名称</td>
                <td>操作</td>
            </tr>
            {% for column in columns %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ column.column }}</td>
                    <td>
                        <a name="edit" href="javascript:" onclick="edit_column(this,{{ column.id }})">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a name="delete" href="javascript:" onclick="del_column(this,{{ column.id }})">
                            <span class="glyphicon glyphicon-trash" style="margin-left: 20px"></span>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <p>还没有设置栏目</p>
            {% endfor %}
        </table>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/layer.js" %}"></script>
    <script>
        function add_column() {
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "新增栏目",
                content: '<div class="text-center" style="margin-top:20px">' +
                '<p>请输入新的栏目名称</p><p>{{ column_form.column }}</p></div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    column_name = $('#id_column').val();
                    $.ajax({
                        url: '{% url "article:article_column" %}',
                        type: 'POST',
                        data: {"column": column_name},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("新增成功");
                            } else {
                                layer.msg("此栏目已存在，请更换名称")
                            }
                        },
                    });
                },
                btn2: function (index, layero) {
                    layer.close(index);
                }
            });
        }

        function edit_column(the, column_id) {
            var name = $(the).parents("tr").children("td").eq(1).text();
            var index = layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "编辑栏目",
                content: '<div class="text-center" style="margin-top:20px"><p>请编辑的栏目名称</p>' +
                '<p><input type="text" id="new_name" value="' + name + '"></p></div>',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    new_name = $("#new_name").val();
                    $.ajax({
                        url: "{% url 'article:rename_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id, "column_name": new_name},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("修改成功");
                            } else {
                                layer.msg("新的名称没有保存,修改失败。")
                            }
                        },
                    });
                },
            });
        }


        function del_column(the, column_id) {
            var name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "编辑栏目",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确认删除{'+name+'}栏目</p></div>',
                btn: ['确定', '取消'],
                yes: function () {
                    $.ajax({
                        url: "{% url 'article:del_article_column' %}",
                        type: "POST",
                        data: {"column_id": column_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("删除成功");
                            } else {
                                layer.msg("删除失败")
                            }
                        },
                    });
                },
            });
        }
    </script>
{% endblock javascript %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}

{% block title %}article list{% endblock %}

{% block content %}
    <div>
        <header>
            <h1 class="text-center">{{ article.title }}</h1>
            <p><span>{{ user.username }}</span><span style="margin-left: 20px">{{ article.created }}</span></p>
        </header>
        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
        <div id="editormd-view">
            <textarea id="append-test" style="display: none">
{{ article.body }}
            </textarea>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>

    <script type="text/javascript">
        $(function () {
            editormd.markdownToHTML("editormd-view",{
                htmlDecode:"style,script,iframe",
                emoji:true,
                taskList:true,
                tex:true,
                flowChart:true,
                sequenceDiagram:true,
            });
        });
    </script>
{% endblock %}

templates/article/column/article_list.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article list{% endblock %}

{% block content %}
    <div>
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>标题</td>
                <td>栏目</td>
                <td>操作</td>
            </tr>
            {% for article in articles %}
                <tr id="{{ article.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
                    <td>{{ article.column }}</td>
                    <td>
                        <span class="glyphicon glyphicon-pencil"></span>
                        <a name="delete" href="javascript:" onclick="del_article(this, {{ article.id }})"><span
                                class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src='{% static "js/jquery-3.2.1.min.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript">
        function del_article(the, article_id) {
            var article_name = $(the).parents("tr").children("td").eq(1).text();
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["400px", "200px"],
                title: "删除文章",
                content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《' + article_name + '》</p></div>',
                btn: ['确定', '取消'],
                yes: function () {
                    $.ajax({
                        url: '{% url "article:del_article" %}',
                        type: "POST",
                        data: {"article_id": article_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("删除成功.");
                            } else {
                                layer.msg("删除失败");
                            }

                        },
                    })
                },
            });
        }
    </script>
{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
    <div style="margin-left:10px">
        <form class="form-horizontal" action="." method="post">
            {% csrf_token %}
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>标题:</span></div>
                <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
            </div>
            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>栏目:</span></div>
                <div class="col-md-10 text-left">
                    <select id="which_column">
                        {% for column in article_columns %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {#        <div class="row" style="margin-top: 10px;">#}
            {#            <div class="col-md-2 text-right"><span>文章标签:</span></div>#}
            {#            <div class="col-md-10 text-left">#}
            {#                {% for tag in article_tags %}#}
            {#                <label class="checkbox-inline">#}
            {#                    <input class="tagcheckbox" type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}"> {{ tag.tag }}#}
            {#                </label>#}
            {#                {% empty %}#}
            {#                <p>You have not type tags for articles. Please <a href="{% url 'article:article_tag' %}">input your tags</a></p>#}
            {#                {% endfor %}#}
            {#            </div>#}
            {#        </div>#}

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-2 text-right"><span>内容:</span></div>
{#                <div class="col-md-10 text-left">{{ article_post_form.body }}</div>#}
                <div id="editormd" class="col-md-10 text-left">
                    <textarea style="display:none;" id="id_body"></textarea>
                </div>
            </div>
            <div class="row">
                <input type="button" class="btn btn-primary btn-lg" value="发布" onclick="publish_article()">
            </div>
        </form>
    </div>
    <script type="text/javascript" src='{% static "js/jquery-3.2.1.min.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
    {#<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>#}
    <script type="text/javascript">
        function publish_article() {
            var title = $("#id_title").val();
            var column_id = $("#which_column").val();
            var body = $("#id_body").val();
            {#    var article_tags = [];#}
            {#    $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});#}
            $.ajax({
                url: "{% url 'article:article_post' %}",
                type: "POST",
                data: {
                    "title": title, "body": body, "column_id": column_id,
                    {#            "tags":JSON.stringify(article_tags)#}
                },
                success: function (e) {
                    if (e == "1") {
                        layer.msg("发布成功");
                        location.href = "{% url 'article:article_list' %}";
                    } else if (e == "2") {
                        layer.msg("文章发布失败.");
                    } else {
                        layer.msg("项目名称或内容不能为空。");
                    }
                },
            });
        }

        $(function () {
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}",
                imageUpload: true,
                {#imageUploadURL:{% url "article/article_post" %}#}
            });
        });
    </script>
{% endblock %}