account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    # url(r'^login/$', views.user_login, name='user_login'),
    url(r'^login/$', auth_views.login, {'template_name': 'account/login.html'}, name='user_login'),
    # url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name='user_register'),
    url(r'^password_change/$', auth_views.password_change,
        {'template_name': 'account/password_change.html', 'post_change_redirect': '/account/password_change_done'},
        name='password_change'),
    url(r'^password_change_done/$', auth_views.password_change_done,
        {'template_name': 'account/password_change_done.html'},
        name='password_change_done'),

    url(r'^my_information/$', views.myself, name='my_information'),
    url(r'^edit_my_information/$', views.myself_edit, name='edit_my_information'),

    url(r'^my_image/$',views.my_image,name='my_image')
]

article/urls.py
from django.conf.urls import url
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^article_column/$', views.article_column, name='article_column'),
    url(r'^rename_column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del_column/$', views.del_article_column, name="del_article_column"),
    url(r'^article_post/$', views.article_post, name="article_post"),
    url(r'^article_list/$', views.article_list, name="article_list"),
    url(r'^article_detail/(?P<id>\d+)/(?P<slug>[-\w]+)$', views.article_detail, name="article_detail"),
    url(r'^del_article/$', views.del_article, name="del_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_article'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

</head>
<body>
    {% include 'header.html' %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'footer.html' %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copyright www.zhouhy.com</p>
</div>

templates/header.html
{% load staticfiles %}

<div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.zhouhy.com">
                <img src="{% static '/images/tenlogo.png' %}" width="100px">
            </a>
        </div>
        <div style="margin-right: 18px">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
{#                <li><a href="{% url 'article:article_titles' %}">文章</a></li>#}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <div class="dropdown" style="margin-top: 8px">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                    data-toggle="dropdown">
                                {{ user.username }}<span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                                <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                                <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                            </ul>
                        </div>
                    </li>
                    {#                    <li><a>Hello,{{ user.username }}.</a></li>#}
                    <li><a href="{% url 'account:user_logout' %}">LOGOUT</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_register' %}">Register</a></li>
                    <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>